### PR TITLE
Add Cloud costs page to user guide Monitoring section

### PR DESCRIPTION
**Pull request by llewellyn-sl**
Per https://github.com/seqeralabs/nf-tower-docs/issues/650

### CODE REVIEW

**Comment by drewdipalma** [comment]
This is a good foundation, but I would like us to have a specific set of recommendations on alerts/budgeting.  If this is just a baseline update and we plan to update further after coordinating with SciDev/Support then LGTM.

**Comment by llewellyn-sl** [comment]
@drewdipalma agreed. I've added support folks to the PR for their input.

**Comment by starnsd** [comment]
Agreed with Drew's input as well as wanting to see this integrated as a high priority warning or maybe even hinted at in the standard install docs or some other similar option. Understood that this is an MVP though and approving as such!

**Review by starnsd — APPROVED** [review]
Agreed with Drew's input as well as wanting to see this integrated as a high priority warning or maybe even hinted at in the standard install docs or some other similar option. Understood that this is an MVP though and approving as such!

**Comment by llewellyn-sl** [comment]
@starnsd thanks! I've added admonitions to the cloud compute environment pages directing users to the cloud costs page. Publishing.

**Pull request merged**
