### PR TITLE
Use Wave git submodule instead of duplicating docs

### PR DESCRIPTION
**Pull request by ewels**
WIP - Adding the Wave git repo as a submodule within the docs repo.

Means that all the markdown can be kept in a single location, rather than being duplicated across two repositories. Much easier to keep in sync, much easier to work with.

> [!CAUTION]
> It looks like the Wave docs in this repo and in the Wave repo are out of sync. I've deleted all files here, but the changes in the docs repo need to be pushed upstream.

Workflow:

- Either edit in [seqeralabs/wave](https://github.com/seqeralabs/wave) directly
- OR edit in `docs/wave_docs/wave_repo`, then `git add` / `git commit` etc. as usual, create a PR on the _Wave_ repo
- We can get the docs website to build nightly and always be pulling in the latest version of the Wave docs.

Taking strategy used in https://github.com/seqeralabs/docs_old/pull/122 and applying to the Wave docs.

@netlify /wave

### CODE REVIEW

**Comment by jason-seqera** [comment]
@ewels, but as I understand it, this just mounts that repository here. While local updates seem possible, it seems to be extraordinarily outside a typical workflow: https://git-scm.com/book/en/v2/Git-Tools-Submodules

Personally I'd want to only make changes in the Wave repo, and only sync the submodule here.

**Comment by jason-seqera** [comment]
@ewels, I think I've settled on this as the best approach, with this being treated basically as a read-only copy of the Wave repo so there's no real confusion or magic involved in where changes should be made.

**Comment by jason-seqera** [comment]
@ewels, won't we need to also adjust any build scripts so that they additional know to clone/pull the sub-module as part of the build?

**Comment by ewels** [comment]
Yes we will, though I'm not sure if Netlify will be do that by default already.

Note that we can also just include `git clone` and `git pull` commands within the `npm run dev` and `npm run build` commands. That'll have roughly the same effect. I did it this way so that changes could be made whilst working within docs and then pushed to Wave (with live previewing of the changes locally). If you're happier making those changes outside of the docs repo environment in a separate clone of the Wave repo, then the git submodule isn't needed and it'd be simpler / cleaner to just do the pull as part of the build.

Does this make sense?

**Comment by ewels** [comment]
So to clarify, my expectation of the workflow with the git submodule was something like this:

1. Run a local dev server for the docs with `npm run dev`
2. In VSCode / another terminal make edits to the regular docs as normal. Commit / PR etc as usual.
3. When editing Wave docs, make sure that the submodule has pulled latest and make the edits in VSCode etc exactly as above with the regular edits. Preview via the dev server in exactly the same way.
4. When wave edits are ready, `cd` into the git submodule and treat it as if you're in a regular clone of the Wave repo. Do `git commit`, branch, open PRs etc from within the submodule to the Wave repo.
5. Deployment previews etc should even respect this, I think. As the submodule reference in the docs repo should point to the correct development branch / sha that's being worked on in Wave. So PRs to the main docs that have a combination of changes across both repos should have accurate previews. I think.

In contrast, if doing as a build step then it's just a case of editing the markdown in the wave the wave repo. Then when merged waiting for the docs repo to rebuild and pull the latest to update. Any local testing will have to be done by copying and pasting / doing a softlink to the repo or something. This is arguably simpler and less prone to breakage, but is less integrated.

**Comment by jason-seqera** [comment]
@ewels, it looks like Netlify pulls sub-modules automatically: https://answers.netlify.com/t/does-netlify-use-pinned-version-of-git-submodule-or-does-it-update-it-re-hugo-theme-as-submodule/113062

**Comment by jason-seqera** [comment]
We've agreed to this approach going forward.

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@ewels, I think we can go ahead and merge this!

**Pull request merged**
