### PR TITLE
PLAT-1057: Fix DS custom env YAML example

### PR DESCRIPTION
**Pull request by jason-seqera**
- https://seqera.atlassian.net/browse/PLAT-1057

Aplies to 24.2, 24.1

### CODE REVIEW

**Comment by jason-seqera** [comment]
cc @robnewman

**Comment by jason-seqera** [comment]
@llewellyn-sl @justinegeffen - Does this look okay? Thanks!

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Looks good to me, thank you!

**Review by robnewman — APPROVED** [review]
Looks good!

**Pull request merged**
