### PR TITLE
Fix YAML for Amazon EKS Ingress

### PR DESCRIPTION
**Pull request by jason-seqera**
This updates the Ingress YAML to match what Amazon expects.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @jason-seqera! What's the best way to validate these changes - for this PR and in general.

**Comment by jason-seqera** [comment]
@justinegeffen, probably someone needs to stand up an entire K8s installation of the product, and probably confirm all functionality. Or at least look at whatever the relevant logs are, for the ingress resource, or in AWS somewhere.

**Review by adriannavarrobetrian — APPROVED** [review]
EKS config is correct and tested.
AKS haven't tested but looks LGTM

**Review by llewellyn-sl — APPROVED** [review]
One fix, the rest LGTM

**Pull request merged**
