### PR TITLE
Make changelog

### PR DESCRIPTION
**Pull request by ewels**
For your automated changelog creation happyness.

Note that it doesn't work well with Seqera Platform, too many release I think.. But maybe good for a starting point at least.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you! How does this work - and how do we troubleshoot it if it breaks? I'd like to add all of the details to the handbook. :D

**Comment by ewels** [comment]
> How does this work

```
bash make_changelog.sh
```

Everything else should hopefully be self-documenting from there on :) Give it a try!

**Comment by justinegeffen** [comment]
Awesome, thanks! Can we merge this independently of https://github.com/seqeralabs/docs/pull/255?

**Comment by ewels** [comment]
> Awesome, thanks! Can we merge this independently of #255?

Yes - I used this script to generate #255 but the two PRs should be independent of one another.

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
