### PR TITLE
google tag manager addition

### PR DESCRIPTION
**Pull request by odagayev**

### CODE REVIEW

**Comment by odagayev** [comment]
image

seeing Google Tag Manager in preview!

**Comment by jason-seqera** [comment]
The plugin: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-tag-manager

**Comment by jason-seqera** [comment]
Can confirm the tag is installed locally:

```
<script>!function(e,t,a,n,g){e[n]=e[n]||[],e[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var m=t.getElementsByTagName(a)[0],r=t.createElement(a);r.async=!0,r.src="https://www.googletagmanager.com/gtm.js?id=GTM-MBCJKK4",m.parentNode.insertBefore(r,m)}(window,document,"script","dataLayer")</script>
```

**Comment by justinegeffen** [comment]
This is great, thanks @odagayev!

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
