### PR TITLE
Update aws-batch.mdx

### PR DESCRIPTION
**Pull request by allyssonallan**
AWS released a [Roles Anywhere](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html) service where you can set the roles in a more precise way to manage specific tools:

https://us-east-1.console.aws.amazon.com/rolesanywhere/home?region=us-east-1

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you for this PR! Editorial review is complete. @adriannavarrobetrian, please could you provide a technical review when you have a gap. Thank you!

**Review by adriannavarrobetrian — COMMENTED** [review]
lgtm

**Review by adriannavarrobetrian — APPROVED** [review]

**Comment by gwright99** [comment]
I'm not grasping how the proposed changes adequately explain Roles Anywhere. 

As per the [Roles Anywhere](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html) link provided, there appears to be a bunch of additional steps needed to make this mechanism work and our docs (appear) to say nothing about it. 

Am I missing something?

**Comment by allyssonallan** [comment]
> I'm not grasping how the proposed changes adequately explain Roles Anywhere.
> 
> As per the [Roles Anywhere](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html) link provided, there appears to be a bunch of additional steps needed (i.e. certificates) to make this mechanism work and our docs (appear) to say nothing about it.
> 
> Am I missing something?

Thanks for your attention and support seqerers! @justinegeffen @adriannavarrobetrian @gwright99 

@gwright99 The point is that 'Roles Anywhere' might provide a ready-to-use authentication once platform set up and deployed for small runs or short term access to cloud resources. It is pretty flexible I think.

**Comment by justinegeffen** [comment]
> @gwright99 The point is that 'Roles Anywhere' might provide a ready-to-use authentication once platform set up and deployed for small runs or short term access to cloud resources. It is pretty flexible I think.

Thank you, @allyssonallan! I'm wondering if we should mention that in this update? If it's something that'll help customers then I don't see why not? If you're open to expanding the update that'd be much appreciated :)

**Comment by allyssonallan** [comment]
> > @gwright99 The point is that 'Roles Anywhere' might provide a ready-to-use authentication once platform set up and deployed for small runs or short term access to cloud resources. It is pretty flexible I think.
> 
> Thank you, @allyssonallan! I'm wondering if we should mention that in this update? If it's something that'll help customers then I don't see why not? If you're open to expanding the update that'd be much appreciated :)

I think it is better to get some @awslabs specialist to introduce the tool, I am not specialist on security and may put the tool in trouble making a mess up to date commit. This one is not linked to this tool, it is to organize thw aws batch docs a bit outdated.

**Comment by gwright99** [comment]
Hi @allyssonallan -- I hope you don't get the sense that I thought your suggestion was a bad idea! (_Quite the opposite, I think Roles Anywhere is a useful tool and have had a few different folks ask me about it_).

My concern with this specific docs PR was just to ensure we have enough information / guidance available to ensure anyone who wants to use the technique with Seqera Platform has a solid appreciation for both (1) what kind of problem the tool can solve, and (2) the additional infrastructure/obligations that would need to be taken on to be able to successfully use it. 

I'll leave it to the Docs team to decide how best to take this forward, but absolutely encourage you to (please) keep contributing your suggestions to make our documentation more helpful for everyone. :)

**Pull request closed without merging**
