### PR TITLE
Update default env var for DE

### PR DESCRIPTION
**Pull request by justinegeffen**
Updates default environment variables for data explorer for enterprise customers.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@ShahzebMahmood, @llewellyn-sl: gentle reminder on this PR. Thank you!

**Comment by justinegeffen** [comment]
@ShahzebMahmood, reminder on this please. :)

**Comment by justinegeffen** [comment]
@llewellyn-sl, when you have a moment, please could you review this. Thanks!

**Review by llewellyn-sl — CHANGES_REQUESTED** [review]
Is this still true? I seem to recall the latest release being default true. Either way, we need to  include 24.1.1 docs for this too, if a change is needed there.

**Comment by justinegeffen** [comment]
> Is this still true? I seem to recall the latest release being default true. Either way, we need to include 24.1.1 docs for this too, if a change is needed there.

Just checked the env vars doc and it supports this change but have also checked with data team.

**Comment by justinegeffen** [comment]
@jimmypoms, ping for a review. Thank you!

**Pull request merged**
